[package]
name = "sddkm-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
shell-escape = "0.1"
anyhow = "1"

[dev-dependencies]
assert_cmd = "2"
